# Generated by Django 3.1 on 2020-10-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenbook',
            name='public_link',
            field=models.CharField(default='example.com', max_length=64, verbose_name='web site'),
        ),
    ]
