# Generated by Django 3.1 on 2020-12-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0004_electron_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrenbook',
            options={'verbose_name': 'Maktab kutubxonasi', 'verbose_name_plural': 'Maktab kutubxonasi'},
        ),
    ]
