# Generated by Django 3.1 on 2020-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0005_auto_20201210_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrenbook',
            options={'verbose_name': 'Maktab kutubxonasi', 'verbose_name_plural': '1. Maktab kutubxonasi'},
        ),
    ]
