# Generated by Django 3.1 on 2021-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0006_auto_20201221_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kitobning nomi')),
                ('author', models.CharField(max_length=150, verbose_name='Kitobning mualifi')),
                ('language', models.CharField(max_length=150, verbose_name='Kitobning matni')),
            ],
            options={
                'verbose_name': 'Kitoblar ro`yxati.',
                'verbose_name_plural': '1.1 Kitoblar ro`yxati.',
            },
        ),
    ]
