# Generated by Django 3.1 on 2020-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(verbose_name='Manzil')),
                ('phone', models.IntegerField(max_length=13, verbose_name='Telefon')),
                ('second_phone', models.IntegerField(blank=True, max_length=13, verbose_name='Ikkinchi telefon (agar bolsa)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('map', models.TextField(verbose_name='Karta')),
            ],
        ),
    ]
