# Generated by Django 3.1 on 2020-09-19 12:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aloqa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aloqa',
            options={'verbose_name': 'Aloqa', 'verbose_name_plural': 'Aloqalar'},
        ),
        migrations.AlterField(
            model_name='aloqa',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='aloqa',
            name='second_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, region=None, verbose_name='Ikkinchi telefon (agar bolsa)'),
        ),
    ]
