# Generated by Django 3.1 on 2020-10-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_savollar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoModule',
        ),
    ]
