# Generated by Django 3.1 on 2020-11-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_nomodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatherAndMother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, verbose_name='Havola')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Joylangan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('photo', models.ImageField(blank=True, upload_to='yangiliklar/%y/%m/%d', verbose_name='OtaOna Surat')),
                ('published', models.BooleanField(default=True, verbose_name='Yuklangan')),
            ],
        ),
    ]
