# Generated by Django 3.1 on 2020-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fatherandmother'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='reklamalar')),
                ('link', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
            },
        ),
        migrations.AlterModelOptions(
            name='fatherandmother',
            options={'verbose_name': 'Ota-onalarga'},
        ),
    ]
