# Generated by Django 3.1 on 2020-12-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201118_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatherandmother',
            options={'verbose_name': 'Ota-ona', 'verbose_name_plural': 'Ota-onalar'},
        ),
    ]
