# Generated by Django 3.1 on 2020-12-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201211_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatherandmother',
            options={'verbose_name': 'Ota-ona', 'verbose_name_plural': 'Ota-onalarga'},
        ),
    ]
