# Generated by Django 3.1 on 2020-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201211_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aloqa',
            options={'verbose_name': 'Aloqa', 'verbose_name_plural': '3. Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='fatherandmother',
            options={'verbose_name': 'Ota-onalarga', 'verbose_name_plural': '2. Ota-onalarga'},
        ),
        migrations.AlterModelOptions(
            name='reklama',
            options={'verbose_name': 'Reklama', 'verbose_name_plural': '4. Reklamalar'},
        ),
        migrations.AlterModelOptions(
            name='savollar',
            options={'verbose_name': 'Savol va Javob', 'verbose_name_plural': '1. Savollar va Javoblar'},
        ),
    ]
