# Generated by Django 3.1 on 2020-12-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Tolmas choy sarlavhasi')),
                ('choy_text', models.TextField(blank=True, verbose_name='Matn')),
            ],
            options={
                'verbose_name': ' Tolmas choy',
                'verbose_name_plural': '6.1 Tolmas Choy',
            },
        ),
        migrations.CreateModel(
            name='DarsJadvali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Jadal joylangan sana')),
                ('jadval', models.ImageField(upload_to='dars_jadvallari/')),
            ],
            options={
                'verbose_name': 'Jadval',
                'verbose_name_plural': '3. Asosiy darslar',
            },
        ),
        migrations.CreateModel(
            name='Jarayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, verbose_name='Havola')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Joylangan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('photo', models.ImageField(blank=True, upload_to='yangiliklar/%y/%m/%d', verbose_name='Jarayon Surat')),
                ('published', models.BooleanField(default=True, verbose_name='Yuklangan')),
            ],
            options={
                'verbose_name': 'Jarayonlar',
                'verbose_name_plural': '4. O`quv Jarayonlari',
            },
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sinf kategoriyasi')),
                ('slug', models.SlugField(unique=True, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Sinf kategoriyasi',
                'verbose_name_plural': '1. Sinf kategoriyalari',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KitchenContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Oshxona sarlavhasi')),
                ('kitchen_text', models.TextField(blank=True, verbose_name='Oshxona texti')),
            ],
            options={
                'verbose_name': 'Oshxona',
                'verbose_name_plural': '6. Oshxona',
            },
        ),
        migrations.CreateModel(
            name='KunTartibi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti. Masalan: 08:45')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti. Masalan: 12:45')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Saytga qo`yilgan vaqti')),
                ('sortings', models.PositiveIntegerField(default=0, verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': 'Kun Tartibi',
                'verbose_name_plural': '2. Kun tartibi',
                'ordering': ['sortings'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=60, verbose_name='O`qituvchi ismi')),
                ('teacher_position', models.CharField(max_length=60, verbose_name='O`qituvchi lavozimi')),
                ('teacher_photo', models.ImageField(upload_to='oqituvchilar/', verbose_name='O`qituvchi surati')),
                ('sortings', models.PositiveIntegerField(default=0, verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': 'O`qituvchi',
                'verbose_name_plural': '5. O`qituvchilar',
                'ordering': ['sortings'],
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, verbose_name='Havola')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Joylangan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('published', models.BooleanField(default=True, verbose_name='Yuklangan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maktab.kategoriya', verbose_name='Sinf')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': '7. Yangiliklar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sinf nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Havola')),
                ('content', models.TextField(blank=True, verbose_name='Sinf haqida qisqacha ma`lumot')),
                ('school_photo', models.ImageField(blank=True, upload_to='sinflar_rasmi/', verbose_name='Sinf surati')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilan vaqti')),
                ('published', models.BooleanField(default=True, verbose_name='Sitega qo`yilgan')),
                ('school_news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maktab.kategoriya', verbose_name='Maktab')),
                ('school_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sinflar', to='maktab.teacher', verbose_name='O`qituvchi')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': '1.1 Sinflar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchen/', verbose_name='Rasm joylashtiring')),
                ('date', models.DateField(verbose_name='Joylangan sana')),
                ('content', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_requests_created', to='maktab.kitchencontent')),
            ],
            options={
                'verbose_name': 'Taomnoma ',
                'verbose_name_plural': 'Taomnoma ',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Sarlavha')),
                ('pictures', models.ImageField(upload_to='oshxona/', verbose_name='Rasm joylashtiring ')),
                ('content', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagegallery_requests_created', to='maktab.kitchencontent')),
            ],
            options={
                'verbose_name': ' Rasmlar ',
                'verbose_name_plural': ' Rasmlar ',
            },
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='choy/', verbose_name='Rasm')),
                ('content', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagecollection_requests_created', to='maktab.choycontent')),
            ],
            options={
                'verbose_name': ' Rasmlar ',
                'verbose_name_plural': ' Rasmlar ',
            },
        ),
        migrations.CreateModel(
            name='Choy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Joylangan sana')),
                ('image', models.ImageField(upload_to='kitchen/choy', verbose_name='Rasm')),
                ('content', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='choy_requests_created', to='maktab.choycontent')),
            ],
            options={
                'verbose_name': ' Tolmas choy',
                'verbose_name_plural': ' Tolmas Choy',
            },
        ),
    ]
