# Generated by Django 3.1 on 2021-01-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jarayon',
            options={'verbose_name': 'Jarayon', 'verbose_name_plural': '4. O`quv Jarayoni'},
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'ordering': ['title'], 'verbose_name': 'Sinf Yangilik', 'verbose_name_plural': '1.2 Sinf Yangiliklari'},
        ),
    ]
