# Generated by Django 3.1 on 2020-09-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, verbose_name='Havola')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, verbose_name='Havola')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Joylangan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('photo', models.ImageField(blank=True, upload_to='yangiliklar/%y/%m/%d', verbose_name='Surat')),
                ('published', models.BooleanField(default=True, verbose_name='Yuklangan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matbuot.kategoriya', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['title'],
            },
        ),
    ]
