# Generated by Django 3.1 on 2020-09-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0004_auto_20200918_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galereya',
            options={'verbose_name': 'Galereya', 'verbose_name_plural': 'Galereya'},
        ),
        migrations.RemoveField(
            model_name='galereya',
            name='sorting',
        ),
    ]
