# Generated by Django 3.1 on 2020-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0005_auto_20200918_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galereya',
            options={'ordering': ['sorting'], 'verbose_name': 'Galereya', 'verbose_name_plural': 'Galereya'},
        ),
        migrations.AddField(
            model_name='galereya',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
