# Generated by Django 3.1 on 2020-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0006_auto_20200918_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galereya',
            options={'ordering': ['sortings'], 'verbose_name': 'Galereya', 'verbose_name_plural': 'Galereya'},
        ),
        migrations.RenameField(
            model_name='galereya',
            old_name='sorting',
            new_name='sortings',
        ),
        migrations.AlterField(
            model_name='galereya',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Qo`yilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='galereya',
            name='image',
            field=models.ImageField(upload_to='galereya/', verbose_name='Upload image'),
        ),
        migrations.AlterField(
            model_name='galereya',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title for photo'),
        ),
    ]
