# Generated by Django 3.1 on 2020-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0007_auto_20200918_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Bo`lim nomi')),
                ('slug', models.SlugField(verbose_name='Ilova')),
                ('image', models.ImageField(upload_to='gallery/%m', verbose_name='Bo`lim surati')),
                ('sortings', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
                'ordering': ['sortings'],
            },
        ),
        migrations.DeleteModel(
            name='Galereya',
        ),
    ]
