# Generated by Django 3.1 on 2020-10-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0008_auto_20201010_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%m', verbose_name='Bo`lim surati')),
                ('sortings', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galereya surati',
                'verbose_name_plural': 'Galereya suratlari',
                'ordering': ['sortings'],
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['sortings'], 'verbose_name': 'Galereya Kategoriya', 'verbose_name_plural': 'Galereya Kategoriyasi'},
        ),
    ]
