# Generated by Django 3.1 on 2020-10-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0009_auto_20201010_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerydetail',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matbuot.gallery', verbose_name='Kategorisyasi'),
        ),
    ]
