# Generated by Django 3.1 on 2020-10-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0010_gallerydetail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydetail',
            name='category',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryDetail',
        ),
    ]
