# Generated by Django 3.1 on 2020-10-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0011_auto_20201012_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(verbose_name='Ilova')),
                ('image', models.ImageField(upload_to='gallery/%m', verbose_name='Bo`lim surati')),
            ],
            options={
                'verbose_name': 'Galereya Kategoriyasi',
                'verbose_name_plural': 'Galereya Kategoriyalari',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Bo`lim nomi')),
                ('slug', models.SlugField(verbose_name='Ilova')),
                ('image', models.ImageField(upload_to='gallery/%m', verbose_name='Bo`lim surati')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matbuot.gallerycategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Galereya surati',
                'verbose_name_plural': 'Galereya suratlari',
                'ordering': ['title'],
            },
        ),
    ]
