# Generated by Django 3.1 on 2020-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0012_gallery_gallerycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['sortings'], 'verbose_name': 'Galereya surati', 'verbose_name_plural': 'Galereya suratlari'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['sortings'], 'verbose_name': 'Galereya Kategoriyasi', 'verbose_name_plural': 'Galereya Kategoriyalari'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='sortings',
            field=models.PositiveIntegerField(default=0, verbose_name='Joylashuv'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='sortings',
            field=models.PositiveIntegerField(default=0, verbose_name='Joylashuv'),
        ),
    ]
