# Generated by Django 3.1 on 2020-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0013_auto_20201012_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, upload_to='gallery/%m', verbose_name='Bo`lim surati'),
        ),
    ]
