# Generated by Django 3.1 on 2020-10-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0014_auto_20201012_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='image/')),
                ('is_active', models.BooleanField(default=True)),
                ('sortings', models.PositiveIntegerField(default=0, verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': 'Galereya Kategoriyasi',
                'verbose_name_plural': 'Galereya Kategoriyalari',
                'ordering': ['sortings'],
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('sortings', models.PositiveIntegerField(default=0, verbose_name='Joylashuv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matbuot.category')),
            ],
            options={
                'verbose_name': 'Galereya surati',
                'verbose_name_plural': 'Galereya suratlari',
                'ordering': ['sortings'],
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
    ]
