# Generated by Django 3.1 on 2020-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0015_auto_20201013_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, verbose_name='Havola')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Joylangan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('photo', models.ImageField(blank=True, upload_to='yangiliklar/%y/%m/%d', verbose_name='Surat')),
                ('published', models.BooleanField(default=True, verbose_name='Yuklangan')),
            ],
        ),
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'ordering': ['title'], 'verbose_name': 'Yangilik  kategoriyai', 'verbose_name_plural': 'Yangilik kategoriyalari'},
        ),
    ]
