# Generated by Django 3.1 on 2020-12-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0016_auto_20201023_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='omv',
            options={'verbose_name': 'OMV biz haqimizda', 'verbose_name_plural': 'OMV biz haqimizda'},
        ),
    ]
