# Generated by Django 3.1 on 2020-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matbuot', '0017_auto_20201210_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sortings'], 'verbose_name': 'Galereya Kategoriyasi', 'verbose_name_plural': '2. Galereya Kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'ordering': ['sortings'], 'verbose_name': 'Galereya surati', 'verbose_name_plural': '2.1 Galereya suratlari'},
        ),
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'ordering': ['title'], 'verbose_name': 'Yangilik  kategoriyai', 'verbose_name_plural': '1. Yangilik kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='omv',
            options={'verbose_name': 'OMV biz haqimizda', 'verbose_name_plural': '3. OMV biz haqimizda'},
        ),
        migrations.AlterModelOptions(
            name='yangiliklar',
            options={'ordering': ['title'], 'verbose_name': 'Yangilik', 'verbose_name_plural': '1.1 Yangiliklar'},
        ),
    ]
