# Generated by Django 3.1 on 2020-10-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='togarakimage',
            options={'verbose_name': 'Togarak surati', 'verbose_name_plural': 'Tugarak suratlari'},
        ),
    ]
