# Generated by Django 3.1 on 2020-10-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0002_auto_20201007_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='togarakimage',
            options={'verbose_name': 'To`garak surati', 'verbose_name_plural': 'To`garak suratlari'},
        ),
        migrations.AlterField(
            model_name='togarakimage',
            name='togarak_photo',
            field=models.FileField(upload_to='togaraklar/%m/', verbose_name='To`garak surati'),
        ),
    ]
