# Generated by Django 3.1 on 2020-10-07 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0003_auto_20201007_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='togaraklist',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Ilova'),
            preserve_default=False,
        ),
    ]
