# Generated by Django 3.1 on 2020-10-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0006_remove_togarakimage_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TogarakImage',
        ),
    ]
