# Generated by Django 3.1 on 2020-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0007_delete_togarakimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='togaraklist',
            name='rasm1',
            field=models.ImageField(default=None, upload_to='togarak/%m', verbose_name='Bitinchi Rasm'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='rasm2',
            field=models.ImageField(default=None, upload_to='togarak/%m', verbose_name='Ikkinchi Rasm'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='rasm3',
            field=models.ImageField(default=None, upload_to='togarak/%m', verbose_name='Uchinchi Rasm'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='rasm4',
            field=models.ImageField(default=None, upload_to='togarak/%m', verbose_name='To`rtinchi Rasm'),
        ),
    ]
