# Generated by Django 3.1 on 2020-11-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0008_auto_20201007_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togaraklist',
            name='rasm1',
            field=models.ImageField(blank=True, null=True, upload_to='togarak/%m', verbose_name='Bitinchi Rasm'),
        ),
        migrations.AlterField(
            model_name='togaraklist',
            name='rasm2',
            field=models.ImageField(blank=True, null=True, upload_to='togarak/%m', verbose_name='Ikkinchi Rasm'),
        ),
        migrations.AlterField(
            model_name='togaraklist',
            name='rasm3',
            field=models.ImageField(blank=True, null=True, upload_to='togarak/%m', verbose_name='Uchinchi Rasm'),
        ),
        migrations.AlterField(
            model_name='togaraklist',
            name='rasm4',
            field=models.ImageField(blank=True, null=True, upload_to='togarak/%m', verbose_name='To`rtinchi Rasm'),
        ),
    ]
