# Generated by Django 3.1 on 2020-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0010_qoshimchadarslist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qoshimchadarslist',
            options={'verbose_name': 'Qoshimcha dars', 'verbose_name_plural': '1. Qo`shimcha darslar'},
        ),
        migrations.AlterModelOptions(
            name='togaraklist',
            options={'verbose_name': 'To`garak', 'verbose_name_plural': '2. To`garaklar'},
        ),
    ]
