# Generated by Django 3.1 on 2021-01-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togaraklar', '0011_auto_20201221_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoshimchadarslist',
            name='videofile1',
            field=models.FileField(blank=True, null=True, upload_to='qoshimchadars/videos/', verbose_name='Video 1'),
        ),
        migrations.AddField(
            model_name='qoshimchadarslist',
            name='videofile2',
            field=models.FileField(blank=True, null=True, upload_to='qoshimchadars/videos/', verbose_name='Video 2'),
        ),
        migrations.AddField(
            model_name='qoshimchadarslist',
            name='videofile3',
            field=models.FileField(blank=True, null=True, upload_to='qoshimchadars/videos/', verbose_name='Video 3'),
        ),
        migrations.AddField(
            model_name='qoshimchadarslist',
            name='videofile4',
            field=models.FileField(blank=True, null=True, upload_to='qoshimchadars/videos/', verbose_name='Video 4'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='videofile1',
            field=models.FileField(blank=True, null=True, upload_to='togarak/videos/', verbose_name='Video 1'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='videofile2',
            field=models.FileField(blank=True, null=True, upload_to='togarak/videos/', verbose_name='Video 2'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='videofile3',
            field=models.FileField(blank=True, null=True, upload_to='togarak/videos/', verbose_name='Video 3'),
        ),
        migrations.AddField(
            model_name='togaraklist',
            name='videofile4',
            field=models.FileField(blank=True, null=True, upload_to='togarak/videos/', verbose_name='Video 4'),
        ),
    ]
