# Generated by Django 3.1 on 2020-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qonun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativ',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
