# Generated by Django 3.1 on 2020-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qonun', '0002_normativ_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maktab_Qoidalari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(verbose_name='Havola')),
                ('content', models.TextField(verbose_name='Maktab Qoidalari')),
            ],
            options={
                'verbose_name': 'Maktab qoidasi',
                'verbose_name_plural': 'Maktab qoidalari',
                'ordering': ['title'],
            },
        ),
    ]
