# Generated by Django 3.1 on 2020-12-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qonun', '0006_auto_20201216_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoidalar',
            name='slug',
        ),
    ]
