# Generated by Django 3.1 on 2020-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qonun', '0007_remove_qoidalar_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normativ',
            options={'ordering': ['title'], 'verbose_name': 'Normativ', 'verbose_name_plural': '2. O`zbekiston davlat Normativlari'},
        ),
        migrations.AlterModelOptions(
            name='qoidalar',
            options={'ordering': ['sarlavha'], 'verbose_name': 'Maktab qoidalari', 'verbose_name_plural': '1. Maktab qoidalari'},
        ),
    ]
